package com.shrenisetu.model;

public enum OnboardingStep {
    ACCOUNT_CREATED,
    PHONE_OR_EMAIL_VERIFIED,
    BASIC_PROFILE_COMPLETED,
    IDENTITY_VERIFICATION_PENDING,
    IDENTITY_VERIFIED,
    CRAFT_PROFILE_COMPLETED,
    ARTWORK_SUBMITTED,
    PROCESS_EVIDENCE_SUBMITTED,
    VERIFICATION_ANALYSIS,
    HUMAN_REVIEW_IF_REQUIRED,
    ARTIST_VERIFIED
}
